config/routes.rb
NameGenerator::Application.routes.draw do

  root 'names#homepage'
  get 'names/generated_names' => 'names#generated_names'
  get 'names/love_calculator' => 'names#generate_love'
  get 'names/sort_out', to: 'names#sort_out'

end

app/models/name.rb
class Name < ActiveRecord::Base

	class <<self
		def test_full_name # OK
			one_name = 0
			two_names = 0
			one_surname = 0
			two_surnames = 0
			name = self.new

			1000.times do
				full_name = name.generate_full_name("Random", "Random", "Random", "Random").split(" ")
				double_surname = full_name.last.split("-").count == 2 ? true : false

				if full_name.count == 2 && !double_surname
					one_name += 1
					one_surname += 1
				elsif full_name.count == 2 && double_surname
					one_name += 1
					two_surnames += 1
				elsif full_name.count == 3 && !double_surname
					two_names += 1
					one_surname += 1
				elsif full_name.count == 3 && double_surname
					two_names += 1
					two_surnames += 1
				end
			end

			{ one_name: one_name,
				two_names: two_names,
				one_surname: one_surname,
				two_surnames: two_surnames }
		end

		def calculate_that_love(alpha_name, beta_name) # OK
			alpha_val = alpha_name.split("").inject(0) { |memo, char| memo += char.ord }
			beta_val = beta_name.split("").inject(0) { |memo, char| memo += char.ord }

			ascii_result = alpha_val > beta_val ? (alpha_val - beta_val) : (beta_val - alpha_val)
			love_value = ascii_result % 100
			love_value != 0 ? love_value : 100
		end

		def split_name_and_surname(full_name) # OK
			full_name = full_name.split(" ")
			double_surname = full_name.last.split("-").count == 2 ? true : false

			if full_name.count == 2
				{ first_name: "#{full_name[0]}", last_name: "#{full_name[1]}"}
			elsif full_name.count == 3 && !double_surname
				{ first_name: "#{full_name[0]} #{full_name[1]}", last_name: "#{full_name[2]}" }
			elsif full_name.count == 3 && double_surname
				{ first_name: "#{full_name[0]} #{full_name[1]}", last_name: "#{full_name[2]}" }
			end
		end

		def sorted_names?(name_collection) # OK
			first_names = []
			surnames = []
			sorted = {
				alpha_asc: false,
				alpha_desc: false,
				beta_asc: false,
				beta_desc: false
			}

			name_collection.each do |full_name|
				first_names << full_name[:first_name].downcase
				surnames << full_name[:last_name].downcase
			end

			if first_names === first_names.sort
				sorted[:alpha_asc] = true
			elsif first_names === first_names.sort.reverse
				sorted[:alpha_desc] = true
			end

			if surnames === surnames.sort
				sorted[:beta_asc] = true
			elsif surnames === surnames.sort.reverse
				sorted[:beta_desc] = true
			end

			sorted
		end

		def sort_it(array, sort_info) # OK
			loop do
				sorted = true
				i = 0
				j = 1

				(array.length - 1).times do
					if sort_info[:ascend]
						if sort_info[:first_name]
							if array[i][:first_name].downcase > array[j][:first_name].downcase
								k = array[j]
								array[j] = array[i]
								array[i] = k
								sorted = false
							end
						else
							if array[i][:last_name].downcase > array[j][:last_name].downcase
								k = array[i]
								array[i] = array[j]
								array[j] = k
								sorted = false
							end
						end
					else
						if sort_info[:first_name]
							if array[i][:first_name].downcase < array[j][:first_name].downcase
								k = array[j]
								array[j] = array[i]
								array[i] = k
								sorted = false
							end
						else
							if array[i][:last_name].downcase < array[j][:last_name].downcase
								k = array[i]
								array[i] = array[j]
								array[j] = k
								sorted = false
							end
						end
					end
					i += 1
					j += 1
				end

				break if sorted
			end

			array
		end
	end

	def generate_full_name(name_count, name_start_letter, surname_count, surname_start_letter) # OK
		name_count = is_random?(name_count)
		name_start_letter = is_random?(name_start_letter)
		surname_count = is_random?(surname_count)
		surname_start_letter = is_random?(surname_start_letter)

		alphabet_array = ('a'..'z').to_a
		alphabet_length = alphabet_array.length

		if name_count == "Random" # 9:91
			(1..9).include?(rand(1..100)) ? name_count = 2 : name_count = 1
		end
		name_start_letter = alphabet_array[rand(0..alphabet_length)] if name_start_letter == "Random"

		if surname_count == "Random" # 5:91
			(1..5).include?(rand(1..100)) ? surname_count = 2 : surname_count = 1
		end
		surname_start_letter = alphabet_array[rand(0..alphabet_length)] if surname_start_letter == "Random"

		if name_count == 1
			name = "#{name_start_letter}"
		else
			first_name, second_name = "#{name_start_letter}", "#{name_start_letter}"
		end

		if surname_count == 1
			surname = "#{surname_start_letter}"
		else
			first_surname, second_surname = "#{surname_start_letter}","#{surname_start_letter}"
		end

		if name && surname
			self.generated = "#{generate_name(name)} #{generate_name(surname)}"
		elsif name && first_surname
			self.generated = "#{generate_name(name)} #{generate_name(first_surname)}-#{generate_name(second_surname)}"
		elsif first_name && surname
			self.generated = "#{generate_name(first_name)} #{generate_name(second_name)} #{generate_name(surname)}"
		elsif first_name && first_surname
			self.generated = "#{generate_name(first_name)} #{generate_name(second_name)} #{generate_name(first_surname)}-#{generate_name(second_surname)}"
		end
	end

	private

	def is_random?(value) # OK
		(value == "Random" || ('a'..'z').include?(value)) ? value : value.to_i
	end

	def generate_name(base_string) # OK
		name_length = rand(3..10)
		possible_letter_type = ["consonant", "vowel"]
		vowels = ['a', 'e', 'i', 'o', 'u']
		consonants = ('a'..'z').to_a - vowels

		vowels.include?(base_string[0]) ? vowel_count = 1 : cons_count = 1

		if vowels.include?(base_string[0])
			vowel_count = 1
			cons_count = 0
		else
			vowel_count = 0
			cons_count = 1
		end

		name_length.times do
			if vowel_count == 1
				base_string << consonants[rand(0..consonants.length - 1)]
				cons_count += 1
				vowel_count = 0
			elsif (cons_count == 2 && name_length > 3) || (cons_count == 1 && name_length == 3)
				base_string << vowels[rand(0..vowels.length - 1)]
				vowel_count += 1
				cons_count = 0
			else
				letter_type = possible_letter_type[rand(0..1)]

				if letter_type == "consonant"
					base_string << consonants[rand(0..consonants.length - 1)]
					cons_count += 1
					vowel_count = 0
				elsif letter_type == "vowel"
					base_string << vowels[rand(0..vowels.length - 1)]
					vowel_count += 1
					cons_count = 0
				end
			end
		end

		base_string.capitalize
	end

end

app/controllers/names_controller.rb
class NamesController < ApplicationController
	before_action :collect_names, only: [:sort_out]

	def homepage
		if valid_params?
			@first_num = params[:first_names_number]
			@first_letter = params[:first_names_letter]
			@last_num = params[:surnames_number]
			@last_letter = params[:surnames_letter]
			@name = Name.new
			generated_name = @name.generate_full_name(@first_num, @first_letter, @last_num,	@last_letter)

			if session[:collected_names]
				if session[:collected_names].count < 10
					session[:collected_names].unshift(generated_name)
				else
					session[:collected_names].pop
					session[:collected_names].unshift(generated_name)
				end
			else
				session[:collected_names] = Array.new.unshift(generated_name)
			end
		end
	end

	def generated_names
		# session[:collected_names] = nil
		# clear names in a session using the upper statement
		if session[:collected_names]
			collect_names

			if @collected_names.size > 1
				@sorted = Name.sorted_names?(@collected_names)
				@names_count= session[:collected_names].size
			else
				@one_name = session[:collected_names][0]
			end
		end
	end

	def generate_love
		name = params[:name]
		alpha = params[:alpha_name]
		beta = params[:beta_name]

		if name
			if name == "alpha"
				@alpha = Name.new.generate_full_name("Random", "Random", "Random", "Random")
				session[:alpha] = @alpha
				session[:beta] ? @beta = session[:beta] : @beta = ""
			else
				@beta = Name.new.generate_full_name("Random", "Random", "Random", "Random")
				session[:beta] = @beta
				session[:alpha] ? @alpha = session[:alpha] : @alpha = ""
			end
		elsif alpha || beta
			if alpha.blank? && beta.blank?
				cash_values(alpha, beta)
				set_cashed_values
				@both_empty = true
			elsif alpha.blank?
				cash_values(alpha, beta)
				set_cashed_values
				@beta = beta
				@no_alpha = true
			elsif beta.blank?
				cash_values(alpha, beta)
				set_cashed_values
				@alpha = alpha
				@no_beta = true
			else
				@alpha = alpha
				@beta = beta
				cash_values(@alpha, @beta)
				@love_result = Name.calculate_that_love(@alpha, @beta)
				@love = "#{@love_result.to_s}%"
				@calculated = true
			end
		else
			set_cashed_values
		end
	end

	def sort_out
		name_part = params[:name_part]
		sort = params[:sort]

		if name_part == "first_name" && sort == "ascend"
			@collected_names = Name.sort_it(@collected_names, first_name: true, ascend: true)
		elsif name_part == "first_name" && sort == "descend"
			@collected_names = Name.sort_it(@collected_names, first_name: true, ascend: false)
		elsif name_part == "last_name" && sort == "ascend"
			@collected_names = Name.sort_it(@collected_names, first_name: false, ascend: true)
		elsif name_part == "last_name" && sort == "descend"
			@collected_names = Name.sort_it(@collected_names, first_name: false, ascend: false)
		end

		@sorted = Name.sorted_names?(@collected_names)
		@names_count = session[:collected_names].count

		render 'generated_names'
	end

	private

	def cash_values(alpha, beta)
		session[:alpha] = alpha
		session[:beta] = beta
	end

	def set_cashed_values
		alpha = session[:alpha]
		beta = session[:beta]

		@alpha = alpha ? alpha : ""
		@beta = beta ? beta : ""
	end

	def collect_names
		@collected_names = session[:collected_names].inject([]) do |memo, full_name|
			memo << Name.split_name_and_surname(full_name)
		end
	end

	def valid_params?
		valid_values = [(1..2), ('a'..'z'), "Random"]
		check_keys = [
			:first_names_number,
			:surnames_number,
			:first_names_letter,
			:surnames_letter
		]

		check_keys.each { |check_key| return false if params[check_key].nil? }

		first_names_num = params[:first_names_number]
		first_names_num = first_names_num.to_i if first_names_num != valid_values[2]
		surnames_num = params[:surnames_number]
		surnames_num = surnames_num.to_i if surnames_num != valid_values[2]
		first_names_letter = params[:first_names_letter]
		surnames_letter = params[:surnames_letter]

		if valid_values[0].include?(first_names_num) || first_names_num == valid_values[2]
			if valid_values[0].include?(surnames_num) || surnames_num == valid_values[2]
				if valid_values[1].include?(first_names_letter) || first_names_letter == valid_values[2]
					if valid_values[1].include?(surnames_letter) || surnames_letter == valid_values[2]
						return true
					end
				end
			end
		end

		false
	end
end

app/helpers/names_helper.rb
module NamesHelper
	def alphabet_values
		('A'..'Z').inject([]) { |memo, letter| memo << [letter, letter.downcase] }.unshift(["Random", "Random"])
	end

	def name_number_values(first_number, last_number)
		(first_number..last_number).inject([]) { |memo, number| memo << [number.to_s, number] }.unshift(["Random", "Random"])
	end

	def anchor(path)
		path + "#anchor"
	end
end

app/views/names/_sorted.html.erb
<th>
	<p>First name</p>
	<center>
		<% if !sorted[:alpha_asc] %>
			<%= link_to("ASC", anchor(names_sort_out_path(name_part: "first_name", sort: "ascend"))) %>
		<% end %>
		<% if !sorted[:alpha_desc] %>
			<%= link_to("DESC", anchor(names_sort_out_path(name_part: "first_name", sort: "descend"))) %>
		<% end %>
	</center>
</th>

<th>
	<p>Last name</p>
	<center>
		<% if !sorted[:beta_asc] %>
			<%= link_to("ASC", anchor(names_sort_out_path(name_part: "last_name", sort: "ascend"))) %>
		<% end %>
		<% if !sorted[:beta_desc] %>
			<%= link_to("DESC", anchor(names_sort_out_path(name_part: "last_name", sort: "descend"))) %>
		<% end %>
	</center>
</th>

app/views/names/generate_love.html.erb
<a id="anchor" href="#"></a>
<% if @calculated %>
<div class="row">
	<center>
		<div class="calculated-love">
			<div id="upper">
				<div class="col-xs-12 col-sm-4">
					<h2 id="first_h2"><%= @alpha %></h2>
				</div>
				<div class="col-xs-12 col-sm-4">
					<% if @love_result >= 0 && @love_result < 25 %>
						<%= image_tag("/love_0_25.png", { size: "200x200" }) %><br>
					<% elsif @love_result >= 25 && @love_result < 50 %>
						<%= image_tag("/love_25_50.png", { size: "200x200" }) %><br>
					<% elsif @love_result >= 50 && @love_result < 75 %>
						<%= image_tag("/love_50_75.png", { size: "200x200" }) %><br>
					<% else %>
						<%= image_tag("/love_75_100.png", { size: "200x200" }) %><br>
					<% end %>
				</div>
				<div class="col-xs-12 col-sm-4">
					<h2 id="last_h2"><%= @beta %></h2>
				</div>
			</div>
			<div class="col-xs-12 col-sm-12">
				<h1><span><%= @love %></span></h1>
			</div>
			<div class="col-xs-12 col-sm-12">
				<%= link_to("New calculation", anchor(names_love_calculator_path)) %>
			</div>
		</div>
	</center>
</div>
<% else %>
	<div class="row">
		<div class="col-xs-12">
			<center>
			<%= form_tag({controller: 'names', action: 'generate_love'}, {method: 'get', id: 'calculate_love_form'}) do %>
				<div class="row">
					<div id="alpha_container" class="col-xs-12 col-sm-4 col-md-3 col-md-offset-1">
						<div class="row">
							<div class="col-xs-12">
								<%= label_tag(:alpha_name, "Type in the first name:")%> <br>
							</div>
							<div class="col-xs-12">
								<%= text_field_tag(:alpha_name, @alpha, size: @alpha.length, value: @alpha, class: "love_names") %><br>
							</div>

							<div class="col-xs-12">
								<h2>OR</h2>
							</div>

							<div class="col-xs-12">
								<%= link_to("Generate first name", names_love_calculator_path(name: "alpha")) %><br>
							</div>
						</div>
					</div>

					<div class="col-xs-12 col-sm-4 col-md-4">
						<%= image_tag("/big_love.jpg", { size: "150x150" }) %>
					</div>

					<div id="beta_container" class="col-xs-12 col-sm-4 col-md-3">
						<div class="row">
							<div class="col-xs-12">
								<%= label_tag(:beta_name, "Type in the second name:")%> <br>
							</div>
							<div class="col-xs-12">
								<%= text_field_tag(:beta_name, @beta, size: @beta.length, value: @beta, class: "love_names") %><br>
							</div>
							
							<div class="col-xs-12">
								<h2>OR</h2>
							</div>

							<div class="col-xs-12">
								<%= link_to("Generate second name", names_love_calculator_path(name: "beta")) %><br>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xs-12">
					<%= submit_tag('Calculate Love', id: "calculate_love_button") %>
				</div>
			<% end %>
			</center>
		</div>
	</div>
<% end %>

app/views/names/generate_love_names.html.erb
<%= form_tag({controller: 'names', action: 'generate_love_names'}, {method: 'get'}) do %>
	<%= hidden_field_tag('alpha', 'create alpha name') %>
	<%= submit_tag('Generate a First Name') %>
<% end %>



<%= form_tag({controller: 'names', action: 'generate_love_names'}, {method: 'get'}) do %>
	<%= hidden_field_tag('beta', 'create beta name') %>
	<%= submit_tag('Generate a Second Name') %>
<% end %>

<h2>OR</h2>

<%= form_tag({controller: 'names', action: 'generate_love'}, {method: 'get'}) do %>
	<%= label_tag(:alpha_name, "Type in the first name:")%> <br>
	<%= text_field_tag(:alpha_name, @alpha, size: @alpha.length) %> <br>

	<h2>OR</h2>

	<%= link_to()%>
	
	<%= label_tag(:beta_name, "Type in the second name:")%> <br>
	<%= text_field_tag(:beta_name, @beta, size: @beta.length) %> <br>

	<h2>OR</h2>

	<%= link_to() %>

	<%= submit_tag('Calculate our Love') %>
<% end %>

app/views/names/generated_names.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
	<a id="anchor" href="#"></a>
	<% if @one_name %>
	<div class="row">
		<center>
			<div class="col-xs-12 one-generated-name">
				<p>Your generated name is:</p>
				<p><%= @one_name %></p>
			</div>
		</center>
	</div>
	<% elsif @collected_names %>
	<table class="table table-hover">
		<thead>
			<%= render partial: "sorted", locals: { sorted: @sorted } %>
		</thead>
		<tfoot>
			<th>Number of names:</th>
			<th><%= @names_count %></th>
		</tfoot>
		<tbody>
			<% @collected_names.each do |full_name|%>
			<tr>
				<td><%= full_name[:first_name] %></td>
				<td><%= full_name[:last_name] %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<% else %>
	<center>
		<div class="row">
			<div class="jumbotron col-xs-12">
				<h1>You <span>didn't generate a name</span> yet...</h1>
			</div>
		</div>
	</center>
	<% end %>
	</div>
</div>

app/views/names/homepage.html.erb
<div class="row">
	<div class="col-xs-12">
		<center>
			<a id="anchor" href="#"></a>
			<h1>Name Generator</h1>
		</center>
	</div>
</div>


		
<% if @name %>
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
			<center id="homepage_main_name">	
				<p id="generated_name"><span><%= @name.generated %></span></p>
			</center>
		</div>
	</div>
<% else %>
	<div class="row">
		<div class="col-xs-12">
			<center id="homepage_main_name">
				<p>Choose your options and click on a new button to generate a <strong>new name</strong>.</p>
			</center>
		</div>
	</div>
<% end %>
	

<div class="row">
	<div class="col-xs-12">
		<center>
				<%= form_tag({controller: 'names', action: 'homepage', class: "form-inline"}, {method: 'get'}) do %>
					<div class="form-group">
						<%= submit_tag('Generate a name') %>
					</div>
					<div class="form-group">
							<%= label_tag(:first_names_number, "Select the number of first names:") %>
							<%= select_tag(:first_names_number, options_for_select(name_number_values(1, 2), @first_num))%> <br>
					</div>
					<div class="form-group">
							<%= label_tag(:surnames_number, "Select the number of last names:") %>
							<%= select_tag(:surnames_number, options_for_select(name_number_values(1, 2), @last_num)) %> <br>
					</div>
					<div class="form-group">
							<%= label_tag(:first_names_letter, "Select the first letter in the name:") %>
							<%= select_tag(:first_names_letter, options_for_select(alphabet_values, @first_letter)) %> <br>
					</div>
					<div class="form-group">
							<%= label_tag(:surnames_letter, "Select the first letter in the surname:") %>
							<%= select_tag(:surnames_letter, options_for_select(alphabet_values, @last_letter)) %> <br>
					</div>
				<% end %>
		</center>
	</div>
</div>